apiVersion: v1
kind: ResourceQuota
metadata:
  name: project-quota
  namespace: __NAMESPACE__
  labels:
    openvre.isolation: "true"
spec:
  hard:
    pods: "80"
    services: "40"
    count/deployments.apps: "40"
    persistentvolumeclaims: "25"
    requests.cpu: "16"
    requests.memory: 32Gi
    limits.cpu: "32"
    limits.memory: 64Gi
    requests.storage: 200Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: project-limits
  namespace: __NAMESPACE__
  labels:
    openvre.isolation: "true"
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      default:
        cpu: "1"
        memory: 1Gi
      max:
        cpu: "8"
        memory: 16Gi
    - type: PersistentVolumeClaim
      max:
        storage: 50Gi
      min:
        storage: 1Gi
