{{- if .Values.components.frontend.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-frontend
  labels:
    app.kubernetes.io/part-of: bsc-tre
---
apiVersion: v1
kind: Secret
metadata:
  name: dashboard-frontend-passwords-secrets
  labels:
    app.kubernetes.io/part-of: bsc-tre
type: Opaque
stringData:
  KEYCLOAK_SECRET: {{ .Values.secrets.frontend.keycloakSecret | quote }}
  MAIL_PASS: {{ .Values.secrets.frontend.mailPass | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dashboard-frontend-env
  labels:
    app.kubernetes.io/part-of: bsc-tre
data:
  FRONTEND_HOST_PATH: {{ .Values.frontend.env.frontendHostPath | quote }}
  KEYCLOAK_CLIENT: {{ .Values.frontend.env.keycloakClient | quote }}
  KEYCLOAK_SERVER: {{ printf "http://dashboard-keycloak.%s.svc.cluster.local:8080/auth" .Release.Namespace | quote }}
  MAIL_HOST: {{ .Values.frontend.env.mailHost | quote }}
  MAIL_USER: {{ .Values.frontend.env.mailUser | quote }}
  MONGO_SERVER: {{ printf "dashboard-mongodb.%s.svc.cluster.local:27017" .Release.Namespace | quote }}
  SERVER_DOMAIN: {{ .Values.domain.host | quote }}
  VAULT_ADDR: {{ printf "http://dashboard-vault.%s.svc.cluster.local:8200" .Release.Namespace | quote }}
  VAULT_API_VERSION: {{ .Values.frontend.env.vaultApiVersion | quote }}
  VAULT_ROLENAME: {{ .Values.frontend.env.vaultRoleName | quote }}
  VAULT_SECRET_PATH: {{ .Values.frontend.env.vaultSecretPath | quote }}
  OPENVRE_K8S_SCHEDULER_URL: {{ printf "http://scheduler.%s.svc.cluster.local:%v" .Release.Namespace .Values.scheduler.service.port | quote }}
  OPENVRE_K8S_SCHEDULER_TOKEN: {{ .Values.scheduler.authToken | quote }}
  OPENVRE_K8S_NAMESPACE: {{ .Release.Namespace | quote }}
  OPENVRE_K8S_SHARED_PVC: {{ .Values.frontend.env.openvreK8sSharedPvc | quote }}
  OPENVRE_K8S_TOOLS_PVC: {{ .Values.frontend.env.openvreK8sToolsPvc | quote }}
  OPENVRE_K8S_RUN_AS_UID: {{ .Values.frontend.env.openvreK8sRunAsUid | quote }}
  OPENVRE_K8S_RUN_AS_GID: {{ .Values.frontend.env.openvreK8sRunAsGid | quote }}
  OPENVRE_K8S_JOB_IMAGE: {{ .Values.frontend.env.openvreK8sJobImage | quote }}
  OPENVRE_K8S_JOB_TTL: {{ .Values.frontend.env.openvreK8sJobTtl | quote }}
  OPENVRE_K8S_JOB_DEADLINE: {{ .Values.frontend.env.openvreK8sJobDeadline | default "86400" | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dashboard-frontend-apache-conf
  labels:
    app.kubernetes.io/part-of: bsc-tre
data:
  server.conf: |
    <VirtualHost *:80>
        ServerName {{ .Values.domain.host | default "localhost" }}
        DocumentRoot /var/www/html/openVRE/public/
        DirectoryIndex index.php
        <Directory "/var/www/html/openVRE/public/api">
            AllowOverride All
            Require all granted
        </Directory>
        ProxyPass "/auth" "http://dashboard-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/auth"
        ProxyPassReverse "/auth" "http://dashboard-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/auth"
        RewriteEngine on
        RewriteRule ^/interactive-tool/([^/]+)/?(.*) https://$1:8090/$2 [P,L]
        ErrorLog /var/log/apache/vre-error.log
        CustomLog /var/log/apache/vre.log combined
    </VirtualHost>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dashboard-frontend-config
  labels:
    app.kubernetes.io/part-of: bsc-tre
data:
  act_qmaster: |
    dashboard-sgecore.{{ .Release.Namespace }}
  globals.inc.php: |
    <?php
    $GLOBALS['BASEURL'] = "/";
    $GLOBALS['AppPrefix'] = "BSC_TRE";
    $GLOBALS['NAME'] = "BSC TRE";
    $GLOBALS['SITETITLE'] = "BSC TRE | Virtual Research Environment";
    $GLOBALS['TIMEOUT'] = 3600;
    $GLOBALS['FROMNAME'] = "VRE";
    $GLOBALS['ADMINMAIL'] = "admin@example.com";
    $GLOBALS['DISKLIMIT'] = 10*1024*1024*1024;
    $GLOBALS['DISKLIMIT_ANON'] = 5*1024*1024*1024;
    $GLOBALS['MAXSIZEUPLOAD'] = 4000;
    $GLOBALS['caduca'] = "182";
    $GLOBALS['project_default'] = "MyFirstProject";
    $GLOBALS['tmpUser_dir'] = ".tmp/";
    $GLOBALS['sampleData_default'] = "basic";
    $GLOBALS['root'] = dirname(__DIR__);
    $GLOBALS['shared'] = "/shared_data/";
    $GLOBALS['logFile'] = $GLOBALS['root']."/logs/application.log";
    $GLOBALS['dataDir'] = $GLOBALS['shared']."userdata/";
    $GLOBALS['pubDir'] = $GLOBALS['shared']."public/";
    $GLOBALS['sampleDataPath'] = "/var/www/html/openVRE/data/sampleData/";
    $GLOBALS['queueTask'] = "local.q";
    $GLOBALS['NETWORK_IP'] = "172.17.0.1";
    $GLOBALS['interactive_range_start_port'] = 9001;
    $GLOBALS['max_parallel_independent_tools'] = 10;
    $GLOBALS['toolsPath'] = "/tools/";
    $GLOBALS['tool_json_schema'] = $GLOBALS['root']."/install/data/tool_schemas/tool_specification/tool_schema.json";
    $GLOBALS['tool_io_json_schema'] = $GLOBALS['root']."/install/data/tool_schemas/tool_specification/tool_schema_io.json";
    $GLOBALS['tool_dev_sample'] = $GLOBALS['root']."/install/data/tool_schemas/tool_specification/examples/example.json";
    $GLOBALS['tool_io_dev_sample'] = $GLOBALS['root']."/install/data/tool_schemas/tool_specification/examples/example_io.json";
    $GLOBALS['compressions'] = array(
        "zip"=>"ZIP","bz2"=>"BZIP2","gz"=>"GZIP","tgz"=>"TAR,GZIP","tar.gz"=>"TAR,GZIP",
        "tbz2"=>"TAR,BZIP2","tar.bz2"=>"TAR,BZIP2","tar.Z"=>"TAR,ZIP","rar"=>"RAR","tar"=>"TAR"
    );
    $GLOBALS['placeholder_input'] = "Click right button to select file";
    $GLOBALS['placeholder_textarea'] = "Click right button to select file(s)";
    $GLOBALS['cloud'] = "local";
    $GLOBALS['clouds'] = array(
        "local" => array(
            "http_host" => "localhost",
            "dataDir_fs" => "/shared_data/userdata/",
            "pubDir_fs" => "/shared_data/public/",
            "dataDir_virtual" => $GLOBALS['dataDir'],
            "pubDir_virtual" => $GLOBALS['pubDir'],
            "dataDir_host" => getenv('FRONTEND_HOST_PATH').$GLOBALS['dataDir'],
            "pubDir_host" => getenv('FRONTEND_HOST_PATH').$GLOBALS['pubDir'],
            "scriptsDir_host" => getenv('FRONTEND_HOST_PATH').$GLOBALS['shared']."scripts/",
            "PMESserver_domain" => "localhost",
            "PMESserver_port" => "80",
            "PMESserver_address" => "/",
            "imageTypes" => array(),
            "auth" => array("required" => False)
        )
    );
    $GLOBALS['ROLES'] = array("0"=>"Admin","1"=>"Tool Dev.","2"=>"Common","3"=>"Anonymous");
    $GLOBALS['NO_GUEST'] = array(0,1,2,100,101);
    $GLOBALS['PREMIUM'] = array(0,1);
    $GLOBALS['ADMIN'] = array(0);
    $GLOBALS['TOOLDEV'] = array(1);
    $GLOBALS['ROLES_COLOR'] = array("0"=>"blue","1"=>"grey-cascade","2"=>"",100=>"red-haze",101=>"yellow-haze");
    $GLOBALS['STATES_COLOR'] = array("0"=>"font-red","1"=>"font-green-meadow","2"=>"font-blue-steel",3=>"font-green-meadow",4=>"font-yellow-mint");
    $GLOBALS['FILE_MSG_COLOR'] = array("0"=>"note-danger","1"=>"note-info","2"=>"note-success",3=>"note-info");
    $scheme = "http";
    if (!empty($_SERVER['HTTP_X_FORWARDED_PROTO'])) {
        $scheme = trim(explode(",", $_SERVER['HTTP_X_FORWARDED_PROTO'])[0]);
    } elseif (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== "off") {
        $scheme = "https";
    }
    $host = !empty($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : getenv('SERVER_DOMAIN');
    $GLOBALS['auth_required'] = True;
    $GLOBALS['authRealm'] = getenv('KEYCLOAK_REALM');
    $authServerInternal = getenv('KEYCLOAK_SERVER');
    $authServerPublic = $scheme . "://" . $host . "/auth";
    $GLOBALS['authServer'] = $authServerInternal;
    $GLOBALS['urlAuthorize'] = $authServerPublic.'/realms/'.$GLOBALS['authRealm'].'/protocol/openid-connect/auth';
    $GLOBALS['urlAccessToken'] = $authServerInternal.'/realms/'.$GLOBALS['authRealm'].'/protocol/openid-connect/token';
    $GLOBALS['urlResourceOwnerDetails'] = $authServerInternal.'/realms/'.$GLOBALS['authRealm'].'/protocol/openid-connect/userinfo';
    $GLOBALS['urlLogout'] = $authServerPublic.'/realms/'.$GLOBALS['authRealm'].'/protocol/openid-connect/logout';
    $GLOBALS['adminToken'] = $authServerInternal."/realms/master/protocol/openid-connect/token";
    $GLOBALS['adminRealm'] = $authServerInternal."/admin/realms/".$GLOBALS['authRealm'];
    $GLOBALS['URL'] = $scheme . "://" . $host . $GLOBALS['BASEURL'];
    $GLOBALS['URL_login'] = $GLOBALS['URL']."login.php";
    $GLOBALS['htmlPath'] = $GLOBALS['root']."/public/";
    $GLOBALS['htmlib'] = $GLOBALS['htmlPath']."htmlib";
    $GLOBALS['appsDir'] = $GLOBALS['shared']."apps/soft/";
    $GLOBALS['internalTools'] = $GLOBALS['shared']."apps/internalTools/";
    $GLOBALS['tool_submission_file'] = ".submit";
    $GLOBALS['tool_config_file'] = ".config.json";
    $GLOBALS['tool_log_file'] = ".tool.log";
    $GLOBALS['tool_stageout_file'] = ".results.json";
    $GLOBALS['tool_metadata_file'] = ".input_metadata.json";
    $GLOBALS['timezone'] = "UTC";
    $GLOBALS['datetime'] = "Y.M.dd HH:mm";
    $GLOBALS['logs_datetime'] = "dd.M.Y HH:mm:ss";
    $GLOBALS['vaultUrl'] = getenv('VAULT_ADDR') . "/" . getenv('VAULT_API_VERSION');
    $GLOBALS['vaultRolename'] = getenv('VAULT_ROLENAME');
    $GLOBALS['secretPath'] = getenv('VAULT_SECRET_PATH');
---
{{- if .Values.frontend.sharedData.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dashboard-frontend-sgecore-shareddata
  labels:
    app.kubernetes.io/part-of: bsc-tre
spec:
  {{- if .Values.frontend.sharedData.persistence.storageClassName }}
  storageClassName: {{ .Values.frontend.sharedData.persistence.storageClassName | quote }}
  {{- end }}
  accessModes:
    - {{ .Values.frontend.sharedData.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.frontend.sharedData.persistence.size | quote }}
---
{{- end }}
{{- if .Values.frontend.tools.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dashboard-frontend-tools
  labels:
    app.kubernetes.io/part-of: bsc-tre
spec:
  {{- if .Values.frontend.tools.persistence.storageClassName }}
  storageClassName: {{ .Values.frontend.tools.persistence.storageClassName | quote }}
  {{- end }}
  accessModes:
    - {{ .Values.frontend.tools.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.frontend.tools.persistence.size | quote }}
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: dashboard-frontend
  labels:
    app.kubernetes.io/part-of: bsc-tre
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: web
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP
  selector:
    app: dashboard-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-frontend
  labels:
    app.kubernetes.io/part-of: bsc-tre
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: dashboard-frontend
  template:
    metadata:
      labels:
        app: dashboard-frontend
    spec:
      serviceAccountName: dashboard-frontend
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: dashboard-init-create-shared-folders
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              mkdir -p /shared_data/public /shared_data/userdata
              chmod -R 0777 /shared_data/public /shared_data/userdata || true
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: frontend-sgecore-shareddata
              mountPath: /shared_data
      containers:
        - name: dashboard-frontend
          image: {{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag }}
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
            allowPrivilegeEscalation: false
          command:
            - bash
            - -c
            - export MONGO_CREDENTIALS="${MONGO_INITDB_USERNAME}:${MONGO_INITDB_PASSWORD}" && /opt/docker/bin/entrypoint.sh supervisord
          envFrom:
            - configMapRef:
                name: dashboard-frontend-env
          env:
            - name: KEYCLOAK_SECRET
              valueFrom:
                secretKeyRef:
                  name: dashboard-frontend-passwords-secrets
                  key: KEYCLOAK_SECRET
            - name: MAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: dashboard-frontend-passwords-secrets
                  key: MAIL_PASS
            - name: KEYCLOAK_REALM
              value: {{ .Values.keycloak.realm | quote }}
            - name: MONGO_TLS_MODE
              value: {{ .Values.dashboardMongo.env.tlsMode | quote }}
            - name: MONGO_MAIN_DB
              value: {{ .Values.dashboardMongo.env.mainDb | quote }}
            - name: MONGO_INITDB_USERNAME
              value: {{ .Values.secrets.dashboardMongo.appUser | quote }}
            - name: MONGO_INITDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dashboard-mongodb-password
                  key: MONGO_INITDB_PASSWORD
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          volumeMounts:
            - name: frontend-sgecore-shareddata
              mountPath: /shared_data
            - name: frontend-tools
              mountPath: /var/www/html/openVRE/public/tools
            - name: conf
              mountPath: /var/www/html/openVRE/config/globals.inc.php
              subPath: globals.inc.php
            - name: conf
              mountPath: /var/lib/gridengine/default/common/act_qmaster
              subPath: act_qmaster
            - name: apache-conf
              mountPath: /opt/docker/etc/httpd/conf.d/10-server.conf
              subPath: server.conf
      volumes:
        - name: frontend-sgecore-shareddata
          persistentVolumeClaim:
            claimName: dashboard-frontend-sgecore-shareddata
        - name: frontend-tools
          persistentVolumeClaim:
            claimName: dashboard-frontend-tools
        - name: apache-conf
          configMap:
            name: dashboard-frontend-apache-conf
            items:
              - key: server.conf
                path: server.conf
        - name: conf
          configMap:
            name: dashboard-frontend-config
            items:
              - key: globals.inc.php
                path: globals.inc.php
              - key: act_qmaster
                path: act_qmaster
---
{{- if .Values.frontend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashboard-frontend
  labels:
    app.kubernetes.io/part-of: bsc-tre
spec:
  ingressClassName: {{ .Values.domain.ingressClassName | quote }}
  rules:
    {{- if .Values.domain.host }}
    - host: {{ .Values.domain.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dashboard-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
    {{- else }}
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dashboard-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
    {{- end }}
{{- if .Values.domain.tlsEnabled }}
  tls:
    - hosts:
        - {{ .Values.domain.host | quote }}
      secretName: {{ .Values.domain.tlsSecretName | quote }}
{{- end }}
{{- end }}
{{- end }}
